```{r, echo=FALSE}
# source('reportEnvironment.R'); build.report("dami_nissinen_2", c(17), do.pdf=TRUE, toc=TRUE);
```
.  

DAMI_2 - algorithm implementation - Mirva Toivonen
=================================================

1. Libraries
-----------
```{r}
library('knitr') 
library('RColorBrewer')
library('arules')
mycolors <- brewer.pal(8, "Dark2")
sessionInfo()
```

2. Own implementation
----------------------
* blah blah 
```{r, results='asis'}
source('arto_implementation.R')
mycat.monospace('arto_implementation.R')
```


3. Trying implementation out
----------------------
```{r, fig.height=3}
minsup <- 0.32 # minimal treshold that still yields a 4-itemset
mink   <- 2    # 1-itemsets are not very interesting
maxk   <- 15   # just something big enough

# Calling the function
courses.tr <- read.transactions('../dami_qame_1/course-text.txt', rm.duplicates=TRUE)
system.time( ret <- arto.apriori(courses.tr, minsup=minsup, mink=mink, maxk=maxk) )
temp <- ret$fisets
inspect(head(sort(temp, by="support"), n=3))
image(items(sort(temp, by="support")))

```
