```{r, echo=F}
source("init1.R")
source("eric/occurrence_matrix.R")
```
Eric's "staging for groupreport"-file
=================================================

Exploratory analysis
--------------------

### Missing course details
Some item ids in `courses_num.txt` don't have an entry in the file
`courses_details.txt`. This means that we don't have any name, year or other
details about these courses. The following item ids have no course details:

```{r}
item.ids <- itemLabels(courses.tr)
indices <- which(sapply(item.ids, function(x) is.null(GetNameForItem(x))))
item.ids[indices]
```
So about `r length(item.ids[indices]) / length(item.ids)` of all items have no
name associated with them.

### Duplicate items
While last week only a couple of transactions had duplicate items, this week
more than half of the transactions have duplicate items.
The following is a distribution of duplicates in transactions:

```{r}
lines <- readLines("courses_num.txt")
lines.of.items <- lapply(lines, split.to.words)
t <- table(sapply(lines.of.items, function(x) length(x) - length(unique(x))))
t
```

So `r t["0"]` transactions have no (0) duplicates, `r t["1"]` transactions have
one duplicate, `r t["2"]` have two duplicates and so on.

An extreme case of this is transaction #846 which contains 158 duplicates. This
may just be an data entry error. Alternatively, this could be an actual student
who has a very unique approach to taking courses. E.g. he or she signs up for
several courses during periods and attends only those that intrest him/her.

```{r}
ind <- which(lapply(lines.of.items, length) > 150)
tr <- lines.of.items[[ind]]
cat("Transaction / Line number", ind)
print(tr)
cat("Number of duplicates", length(tr) - length(unique(tr)))
```

### Number of students enrolled vs. years taught
```{r}
total.years <- sapply(years.held, function(years) {
  max(years) - min(years) + 1
})

item.freqs <- itemFrequency(courses.tr, type="absolute")
res <- total.years[names(item.freqs)]
xs <- res[complete.cases(res)] # Note: NAs dropped

ys <- item.freqs[names(xs)]

names(xs) <- NULL
names(ys) <- NULL
plot(xs, ys, ylab="Number of students enrolled",
     xlab="Total number of years held",
     main="Scatterplot of courses")
```
Algorithm related findings
--------------------------

Substance data findings
--------------------------
