<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Data Mining Problem 2 - QAME Group Report</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>




</head>

<body>
<pre><code>## Error: there is no package called &#39;RColorBrewer&#39;
</code></pre>

<pre><code>## Error: could not find function &quot;sourceCpp&quot;
</code></pre>

<pre><code>## Error: could not find function &quot;read.transactions&quot;
</code></pre>

<pre><code>## Error: could not find function &quot;read.transactions&quot;
</code></pre>

<pre><code>## Error: object &#39;courses.tr&#39; not found
</code></pre>

<pre><code>## Error: object &#39;courses.tidlists&#39; not found
</code></pre>

<pre><code>## Error: could not find function &quot;ReadInData&quot;
</code></pre>

<pre><code>## Error: could not find function &quot;convert.item.ids.to.names&quot;
</code></pre>

<h1>Data Mining Problem 2 - QAME Group Report</h1>

<p>This problem 2 report submission consists of five different parts: this group report that is more results focused and the four individual reports (already turned in) that are more algorithm focused. Reader is welcome to read the individual reports for further details that are not repeated here.</p>

<p>We begin with group-learning related issues and then proceed to substance.</p>

<h2>Group learning and self evaluation</h2>

<h3>Learning objectives for this problem</h3>

<p>In addition to concept understanding goals (maximal and closed itemsets, association rules, interestingness measures and depth-first vs breadth-first algorithms) presented further in the research questions, we wanted to utilize the feedback and experience from previous problem to make our report more accessible. For example we used different finishing process to be able to make figures appear nearer the text that addresses them. We also stated our research goals more clearly. </p>

<h3>Organizing studying, learning and working</h3>

<p>We meet after lectures and organize our work face to face. We found it more effective to work face to face and discuss about learning goals, results and findings. We tried to divide focus areas so that we would have different algorithms implemented and we could compare them. However, estimating the difficulty level of different choices proved to be quite difficult. We could try to improve this work division and goal setting process.</p>

<p>We identified the rest of the chapter 6 from the course book as beneficial in order to reach our learning goals. After that group members studied and tried to implement their chosen algorithms mostly independently. After Monday’s lecture we started to produce the group report by each member developing mini-reports on particular subjects for others to see via git. Finally, we composed a coherent whole of these mini-reports. We found this approach satisfactory.</p>

<p>Different members of the group found different things difficult. We were able to teach each other something. We were also able to share some useful functions via github and improve on the work of others. These things helped us enjoy working as a group.</p>

<h2>Research questions</h2>

<p>We sought answers to the following questions.</p>

<ul>
<li><p>How does this data set compare to the previous one. Does it have the same
kind of problems (e.g. duplicates) as the last set? What can we infer from the
additional information?</p></li>
<li><p>Effectiveness of depth-first vs. breadth-first approaches to mining frequent
itemsets, or in a nutshell: which one is faster, Apriori or Eclat?</p></li>
<li><p>How much worse (or better) our implementations of the algorithms perform
compared to the &ldquo;arules&rdquo; R library&#39;s implementations?</p></li>
<li><p>How many of the mined frequent itemsets turn out to be closed, how many
were maximal?</p></li>
<li><p>How do the results of different interestingness measures compare?</p></li>
</ul>

<h2>Exploratory analysis</h2>

<h3>Most frequent courses</h3>

<p>Below are outlined the most frequent courses (support greater than 0.08).</p>

<pre><code>## Error: object &#39;courses.tr&#39; not found
</code></pre>

<pre><code>## Error: object &#39;lab&#39; not found
</code></pre>

<pre><code>## Error: object &#39;temp&#39; not found
</code></pre>

<pre><code>## Error: could not find function &quot;itemFrequencyPlot&quot;
</code></pre>

<h3>Skewness of support distribution</h3>

<pre><code>## Error: could not find function &quot;itemFrequency&quot;
</code></pre>

<pre><code>## Error: object &#39;item.freqs&#39; not found
</code></pre>

<pre><code>## Error: object &#39;item.freqs&#39; not found
</code></pre>

<p>Above is plotted the support of each item in increasing order of support.
Notice that the x-axis is not the TID but rather the rank of the item in the
ordering.  Out of all </p>

<pre><code>
Error in eval(expr, envir, enclos) : object &#39;item.freqs&#39; not found

</code></pre>

<p>items, </p>

<pre><code>
Error in eval(expr, envir, enclos) : object &#39;item.freqs&#39; not found

</code></pre>

<p>have a support lower than 1%, </p>

<pre><code>
Error in eval(expr, envir, enclos) : object &#39;item.freqs&#39; not found

</code></pre>

<p>items have a support
higher than 10%. Highest support is </p>

<pre><code>
Error in tail(item.freqs, n = 1) : object &#39;item.freqs&#39; not found

</code></pre>

<p>.</p>

<p>Whether this skewness is a problem or not is hard to say without experience.
Visually this seems very worrying, but on the other hand the example given in
the book (p. 386) is much worse.</p>

<h3>Missing course details</h3>

<p>Some item ids in <code>courses_num.txt</code> don&#39;t have an entry in the file
<code>courses_details.txt</code>. This means that we don&#39;t have any name, year or other
details about these courses. The following item ids have no course details:</p>

<pre><code>## Error: could not find function &quot;itemLabels&quot;
</code></pre>

<pre><code>## Error: object &#39;item.ids&#39; not found
</code></pre>

<pre><code>## Error: object &#39;item.ids&#39; not found
</code></pre>

<p>So about </p>

<pre><code>
Error in eval(expr, envir, enclos) : object &#39;item.ids&#39; not found

</code></pre>

<p>of all items have no
name associated with them.</p>

<h3>Duplicate items</h3>

<p>While last week only a couple of transactions had duplicate items, this week
more than half of the transactions have duplicate items.
The following is a distribution of duplicates in transactions:</p>

<pre><code>## 
##    0    1    2    3    4    5    6    7    8    9   10   11   12   13   14 
## 4022 1244  675  487  329  254  210  188  129  109   99   80   73   64   65 
##   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29 
##   49   39   37   37   38   25   26   27   12   14   15   11   18    9   12 
##   30   31   32   33   34   35   36   37   38   39   40   41   43   44   45 
##    9    2    6    2    3    3    4    4    4    3    4    1    3    1    2 
##   47   48   49   50   54   55   61   66   70   75  158 
##    1    2    2    2    2    1    2    2    1    1    1
</code></pre>

<p>So 4022 transactions have no (0) duplicates, 1244 transactions have
one duplicate, 675 have two duplicates and so on.</p>

<p>An extreme case of this is transaction #846 which contains 158 duplicates. This
may just be an data entry error. Alternatively, this could be an actual student
who has a very unique approach to taking courses. E.g. he or she signs up for
several courses during periods and attends only those that interest him/her.
Below is the full list of courses this student enrolled to.</p>

<pre><code>## Transaction / Line number 846
</code></pre>

<pre><code>##   [1] &quot;5&quot;   &quot;31&quot;  &quot;35&quot;  &quot;44&quot;  &quot;52&quot;  &quot;52&quot;  &quot;52&quot;  &quot;52&quot;  &quot;52&quot;  &quot;52&quot;  &quot;52&quot; 
##  [12] &quot;61&quot;  &quot;72&quot;  &quot;72&quot;  &quot;72&quot;  &quot;75&quot;  &quot;75&quot;  &quot;77&quot;  &quot;77&quot;  &quot;77&quot;  &quot;77&quot;  &quot;77&quot; 
##  [23] &quot;77&quot;  &quot;77&quot;  &quot;77&quot;  &quot;80&quot;  &quot;80&quot;  &quot;80&quot;  &quot;80&quot;  &quot;80&quot;  &quot;80&quot;  &quot;80&quot;  &quot;80&quot; 
##  [34] &quot;80&quot;  &quot;83&quot;  &quot;83&quot;  &quot;84&quot;  &quot;84&quot;  &quot;84&quot;  &quot;85&quot;  &quot;86&quot;  &quot;86&quot;  &quot;86&quot;  &quot;86&quot; 
##  [45] &quot;86&quot;  &quot;86&quot;  &quot;87&quot;  &quot;89&quot;  &quot;89&quot;  &quot;89&quot;  &quot;89&quot;  &quot;89&quot;  &quot;89&quot;  &quot;89&quot;  &quot;89&quot; 
##  [56] &quot;89&quot;  &quot;89&quot;  &quot;89&quot;  &quot;89&quot;  &quot;89&quot;  &quot;89&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot; 
##  [67] &quot;91&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot;  &quot;91&quot; 
##  [78] &quot;92&quot;  &quot;92&quot;  &quot;92&quot;  &quot;92&quot;  &quot;92&quot;  &quot;92&quot;  &quot;92&quot;  &quot;92&quot;  &quot;92&quot;  &quot;92&quot;  &quot;92&quot; 
##  [89] &quot;93&quot;  &quot;93&quot;  &quot;93&quot;  &quot;93&quot;  &quot;93&quot;  &quot;93&quot;  &quot;94&quot;  &quot;94&quot;  &quot;94&quot;  &quot;98&quot;  &quot;98&quot; 
## [100] &quot;98&quot;  &quot;98&quot;  &quot;98&quot;  &quot;98&quot;  &quot;98&quot;  &quot;98&quot;  &quot;98&quot;  &quot;98&quot;  &quot;98&quot;  &quot;99&quot;  &quot;99&quot; 
## [111] &quot;101&quot; &quot;103&quot; &quot;108&quot; &quot;108&quot; &quot;108&quot; &quot;109&quot; &quot;109&quot; &quot;109&quot; &quot;131&quot; &quot;193&quot; &quot;193&quot;
## [122] &quot;193&quot; &quot;193&quot; &quot;193&quot; &quot;194&quot; &quot;201&quot; &quot;206&quot; &quot;206&quot; &quot;206&quot; &quot;206&quot; &quot;206&quot; &quot;206&quot;
## [133] &quot;206&quot; &quot;206&quot; &quot;206&quot; &quot;206&quot; &quot;206&quot; &quot;206&quot; &quot;208&quot; &quot;208&quot; &quot;208&quot; &quot;208&quot; &quot;208&quot;
## [144] &quot;208&quot; &quot;208&quot; &quot;265&quot; &quot;265&quot; &quot;265&quot; &quot;265&quot; &quot;265&quot; &quot;265&quot; &quot;265&quot; &quot;265&quot; &quot;267&quot;
## [155] &quot;267&quot; &quot;267&quot; &quot;267&quot; &quot;267&quot; &quot;279&quot; &quot;279&quot; &quot;279&quot; &quot;279&quot; &quot;279&quot; &quot;279&quot; &quot;303&quot;
## [166] &quot;303&quot; &quot;303&quot; &quot;303&quot; &quot;303&quot; &quot;307&quot; &quot;307&quot; &quot;307&quot; &quot;307&quot; &quot;339&quot; &quot;339&quot; &quot;339&quot;
## [177] &quot;339&quot; &quot;339&quot; &quot;339&quot; &quot;339&quot; &quot;339&quot; &quot;339&quot; &quot;347&quot; &quot;347&quot; &quot;347&quot; &quot;347&quot; &quot;347&quot;
## [188] &quot;348&quot; &quot;362&quot; &quot;396&quot; &quot;398&quot; &quot;402&quot; &quot;402&quot; &quot;402&quot; &quot;402&quot; &quot;402&quot; &quot;402&quot; &quot;402&quot;
## [199] &quot;402&quot; &quot;402&quot; &quot;402&quot; &quot;402&quot;
</code></pre>

<pre><code>## Number of duplicates 158
</code></pre>

<h3>Number of students enrolled vs. years taught</h3>

<pre><code>## Error: object &#39;years.held&#39; not found
</code></pre>

<pre><code>## Error: could not find function &quot;itemFrequency&quot;
</code></pre>

<pre><code>## Error: object &#39;total.years&#39; not found
</code></pre>

<pre><code>## Error: object &#39;res&#39; not found
</code></pre>

<pre><code>## Error: object &#39;item.freqs&#39; not found
</code></pre>

<pre><code>## Error: object &#39;xs&#39; not found
</code></pre>

<pre><code>## Error: object &#39;ys&#39; not found
</code></pre>

<pre><code>## Error: object &#39;xs&#39; not found
</code></pre>

<p>From the additional data file we could find the specific years a course has
been held and thus infer the total number of years it has been held. Note here
that we&#39;re assuming that all relevant years are reported in the additional data.
This is most likely a naive belief, especially given the quality of the data
so far, nevertheless it&#39;s a useful approximation.</p>

<p>From the plot above, we can see that the total years a course has been held
definitely impacts the number of students who have enrolled to it. But this
doesn&#39;t automatically imply that the number of enrollments will be high, rather
it is just a precondition for it to be possible.</p>

<h2>Algorithm related findings</h2>

<h3>Comparison of depth-first vs breadth-first</h3>

<p>From the plot below we can see that depth first counts supports from data to more itemsets but seems to runs faster anyway. We think that support-counting from TID-lists is just so much faster than from &ldquo;horizontal&rdquo; data. </p>

<p>We were also thinking that maybe depth-first search would benefit from ordering the items in increasing order of frequency. This is because the more right we are on the search tree the less supersets we have to check. And maybe the ordering would make the tree more right-weighted. </p>

<pre><code>## Error: object &#39;courses.tr.old&#39; not found
</code></pre>

<pre><code>## Error: &#39;data&#39; must be of a vector type
</code></pre>

<pre><code class="r">barplot(tim, beside = TRUE, log = &quot;y&quot;, ylab = &quot;runtime (seconds)&quot;, main = &quot;Runnning times&quot;)
</code></pre>

<pre><code>## Error: log scale error: at least one &#39;height + offset&#39; value &lt;= 0
</code></pre>

<p>Running times of different algorithm implementations are shown above. For each
of the four cases, the first two bars corresponds to support thresholds of 0.23
and 0.15 on last week&#39;s data, while the last two bars corresponds to
thresholds 0.12 and 0.08 on this week&#39;s data.</p>

<h3>Number of non-closed itemsets and data density</h3>

<h4>Density difference between old and new data set visualization</h4>

<p>Old datasets density, 0.130863, is much bigger than the new dataset&#39;s density, 0.02010921. The visualizations below are samples from the beginning of data-matrix sorted in a such way that the most frequent courses are at the left and the students who took the most courses are at the top. </p>

<pre><code>## Error: object &#39;courses.tr.old&#39; not found
</code></pre>

<pre><code>## Error: object &#39;courses.tr&#39; not found
</code></pre>

<h4>Frequent, closed and maximal itemsets and 1-rules</h4>

<p>In the new dataset we observe that almost all of the frequent itemsets are also closed itemsets. This is indicated by the fact that the &ldquo;frequent&rdquo;-line and &ldquo;closed&rdquo;-line are almost overlapping in the plot below. Threshold has to be set to 0.08 to get at least some non-closed frequent itemsets. Even setting the threshold to 0.04 does not yield many non-closed itemsets, as we can see from the plot below (note that in the plot the rules include only rules that have consequents of size 1). </p>

<p>The old dataset on comparison had much more non-closed itemsets as we can see from the plots. We thought that this could be related to the fact that old datasets density, 0.130863, is much bigger than the new dataset&#39;s density, 0.02010921. </p>

<pre><code>## Error: could not find function &quot;eclat&quot;
</code></pre>

<pre><code>## Error: object &#39;bm&#39; not found
</code></pre>

<pre><code>## Error: could not find function &quot;eclat&quot;
</code></pre>

<pre><code>## Error: object &#39;bm&#39; not found
</code></pre>

<pre><code>## Error: could not find function &quot;eclat&quot;
</code></pre>

<pre><code>## Error: object &#39;bm&#39; not found
</code></pre>

<pre><code>## Error: could not find function &quot;eclat&quot;
</code></pre>

<pre><code>## Error: object &#39;bm&#39; not found
</code></pre>

<h3>Interestingness measures comparison</h3>

<h4>Non-closed frequent itemsets and rule-confidence=1 relation</h4>

<p>With support threshold=0.08 we get 6 itemsets that are not closed frequent. These itemsets are exactly the rule antecedents (left hand sides, LHS) of the only 1-consequent-rules that have confidence of 1 as we can see from output below. This means unioning these LHS with the rule consequent (right hand sides, RHS), item 80 (data_structures) in this case, we get itemsets whose supports are exactly the same as LHS alone. Therefore these LHS+RHS union itemsets are closed itemsets that close over their respective LHS-part (which are not closed themselves).</p>

<p>Also, Items 131 (introduction_to_the_use_of_computers), 194 (data_structures_project) and 83 (introduction_to_programming) appear in all of those 6 itemsets. But a rule {131,194,83} =&gt; {80} has a confidence of 0.9973118. This means that the itemset {131,194,83} have slightly higher support than the combined itemset {131,194,83,80}. Also, by knowing that {131,194,83} is not a closed itemset, we could immediately say that all of it&#39;s supersets must have lower support than it.</p>

<p>Another interesting question is why are the lifts the same?</p>

<pre><code class="r">bm &lt;- myget.allbm(courses.tr, 0.08, minconfidence)
</code></pre>

<pre><code>## Error: could not find function &quot;eclat&quot;
</code></pre>

<pre><code class="r">as(setdiff(bm$fisets, bm$closed), &quot;data.frame&quot;)
</code></pre>

<pre><code>## Error: object &#39;bm&#39; not found
</code></pre>

<pre><code class="r">as(head(sort(bm$rules, by = &quot;confidence&quot;), n = 30), &quot;data.frame&quot;)
</code></pre>

<pre><code>## Error: object &#39;bm&#39; not found
</code></pre>

<pre><code class="r">inspect(head(mynamify(sort(bm$rules, by = &quot;confidence&quot;), lab), n = 1))
</code></pre>

<pre><code>## Error: could not find function &quot;inspect&quot;
</code></pre>

<h4>Top ranked by allconfidence vs lift</h4>

<p>Definition: &ldquo;allConfidence (see, Omiencinski, 2003) is defined on itemsets as the minimum confidence of all possible rule generated from the itemset.&rdquo; [arules vignette]. In other words, these items tend to appear together. Lift is P(R|L)/P&reg;. These two seem to give quite similar intuition, at least in this run.</p>

<pre><code>## Error: object &#39;bm&#39; not found
</code></pre>

<pre><code>## Error: could not find function &quot;interestMeasure&quot;
</code></pre>

<pre><code>## Error: could not find function &quot;quality&quot;
</code></pre>

<pre><code>## Error: could not find function &quot;items&quot;
</code></pre>

<pre><code>## Error: could not find function &quot;quality&quot;
</code></pre>

<pre><code>## Error: object of type &#39;closure&#39; is not subsettable
</code></pre>

<pre><code>## Error: object &#39;ex&#39; not found
</code></pre>

<pre><code>## Error: object &#39;fisets&#39; not found
</code></pre>

<pre><code>## Error: object &#39;bm&#39; not found
</code></pre>

<pre><code class="r">inspect(top.allConfidence)
</code></pre>

<pre><code>## Error: could not find function &quot;inspect&quot;
</code></pre>

<pre><code class="r">inspect(mynamify(head(sort(bm$rules, by = &quot;lift&quot;), n = 8), lab))
</code></pre>

<pre><code>## Error: could not find function &quot;inspect&quot;
</code></pre>

<h3>Other observations</h3>

<p>For most of the experiments with Apriori we used a support threshold of 0.08
because that yielded at least some non-closed itemsets which could be analyzed
further.  However setting the threshold this low, especially with this data
set, caused us some problems with performance.</p>

</body>

</html>

