% !Rnw root = ../reports/dami_qame_4_slides.Rnw

\begin{frame}[fragile]
\frametitle{Comparisons}

% \begin{multicols}{2}

\begin{itemize}
\item with minsup 0.25 infrequent X U Y has to have frequent negative pattern (conttab sum =1)
\item many neg.cor patterns have corresponding neg. patterns Inequality 7.6 and table 7.9
\item infreq neg.cor patterns tend to be more interesting then frequent... hmmm
\end{itemize}

% \end{multicols}

\end{frame}