% !Rnw root = ../reports/dami_qame_3_report.Rnw

<<arto_implementation_comput, results=hide>>=
source("../arto/arto_implementation_comput.R")
@

\subsection{Arto implementation}
\begin{multicols}{2}

Results from reference implementation:

<<arto_implementation_out1, results=verbatim>>=
arto_implementation.list$outme1()
@

My results:

<<arto_implementation_out2, results=verbatim>>=
arto_implementation.list$outme2()
@


\end{multicols}