% !Rnw root = ../reports/dami_qame_3_report.Rnw

<<examples_with_library_comput, results=hide>>=
source("../arto/examples_with_library_comput.R")
@

\subsection{Examples with library}
\begin{multicols}{2}
\end{multicols}

Top lift rules:

<<examples_with_library_out1, results=verbatim>>=
oldopts <- options("width")
options(width=120)
arto1$outme1()
options(width=oldopts$width)
@

% My results:
% 
% <<examples_with_library_out2, results=verbatim>>=
% examples_with_library.list$outme2()
% @
