```{r, echo=FALSE}
# source('reportEnvironment.R'); build.report(c(2,3), do.pdf=TRUE);
```
.  

3. Reading the data in and exploring it
------

### Data-rows have duplicates:
```{r}
courses.tr <- read.transactions('course-text.txt', rm.duplicates=TRUE)
```
.   

### Data has 99 unique course-labels, not 106 as README.txt claims:
```{r}
summary(courses.tr)
# colnames(courses.tr)
```
.  

### Courses are not evenly distributed:
```{r, fig.width=10, fig.height=6}
image(courses.tr[1:100, ])
# Columns are courses and rows are students
itemFrequencyPlot(courses.tr, support = 0.0, cex.names=0.5, main="Course frequencies")
histogram(size(courses.tr), type="count", main="Histogram of how many courses each student took", col=mycolors[7])
```
. 

### Effect of support treshold on the number of frequent itemsets:
```{r, fig.width=10, fig.height=6, results='hide'}
fisets005 <- eclat(courses.tr, parameter=list(support=0.05, maxlen=99))
fisets010 <- eclat(courses.tr, parameter=list(support=0.10, maxlen=99))
fisets020 <- eclat(courses.tr, parameter=list(support=0.20, maxlen=99))
tabu005 <- tabulate(size(fisets005))
tabu010 <- tabulate(size(fisets010))
tabu020 <- tabulate(size(fisets020))
counts <- matrix(1,length(tabu005),3)
counts[1:length(tabu005),1] <- tabu005
counts[1:length(tabu010),2] <- tabu010
counts[1:length(tabu020),3] <- tabu020
matplot(counts, pch=1:3, lwd=2, col=mycolors,type="b", log="y", xlab="size of itemset", ylab="Number of frequent itemsets", main="Effect of support treshold on the number of frequent itemsets")
grid(lty=2)
legend("bottomleft", pch=1:3, lwd=2, lty=1:3, col=mycolors, legend=c(paste("treshold=",c(0.05, 0.10, 0.20), sep="")))
```
